trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: test_config.R
  - name: CredFileLibrary
    value: product-readiness.piwebapi_r.R
  - name: analysisProject
    value: PIWebAPI_R

parameters:
  - name: pool
    default: 00-OSIManaged-Build
  - name: containerDemands
    type: object
    default: ['R -gtVersion 4.1.3']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - template: '/run-tests.yml'
        parameters:
          projectPath: $(Build.SourcesDirectory)

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      skipPolaris: true
